<?php

return [
    'permissions' => [
        'employees.view_any',
        'employees.manage',
        'attendance.view_any',
        'attendance.manage',
        'attendance.punch',
        'leaves.view_any',
        'leaves.manage',
        'payroll.view_any',
        'payroll.manage',
        'reports.view',
        'recruitment.manage',
        'performance.manage',
        'documents.manage',
        'organization.manage',
    ],
    'roles' => [
        'admin' => [
            'employees.view_any',
            'employees.manage',
            'attendance.view_any',
            'attendance.manage',
            'attendance.punch',
            'leaves.view_any',
            'leaves.manage',
            'payroll.view_any',
            'payroll.manage',
            'reports.view',
            'recruitment.manage',
            'performance.manage',
            'documents.manage',
            'organization.manage',
        ],
        'hr' => [
            'employees.view_any',
            'employees.manage',
            'attendance.view_any',
            'attendance.manage',
            'leaves.view_any',
            'leaves.manage',
            'payroll.view_any',
            'payroll.manage',
            'reports.view',
            'recruitment.manage',
            'performance.manage',
            'documents.manage',
            'organization.manage',
        ],
        'employee' => [
            'attendance.punch',
        ],
    ],
    'applicant_stages' => [
        'applied',
        'screening',
        'interview_scheduled',
        'interviewed',
        'offered',
        'hired',
        'rejected',
    ],
    'leave_statuses' => [
        'pending',
        'approved',
        'rejected',
        'cancelled',
    ],
    'payroll_statuses' => [
        'draft',
        'processed',
        'released',
    ],
    'review_statuses' => [
        'draft',
        'submitted',
        'acknowledged',
    ],
    'attendance' => [
        'minimum_accuracy_meters' => 100,
    ],
    'payroll' => [
        'cutoffs' => [
            ['start_day' => 1, 'end_day' => 15],
            ['start_day' => 16, 'end_day' => 31],
        ],
    ],
];
